services:
  nest-demo:
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgresdb
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
