name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ##ClONE CODE
      - name: Checkout CODE
        uses: actions/checkout@v2
      ## DEPLOY TO RENDER
      - name: deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_KEY }}
